### ISSUE TITLE
How to set cell style in stream writer 数据量比较大时，格式问题

### ISSUE THREAD

**Issue by changgong1** [xuri/excelize-doc#25]
流提供了SetRow函数，当每列格式不一样时，是否有针对不同单元格写入格式的函数。

**Comment by xuri** [comment]
Thanks for your issue. Please reference the [example](https://xuri.me/excelize/zh-hans/stream.html#NewStreamWriter) in documentation, you can set each cell's style by specify `StyleID` field in `Cell` data type.

谢谢你的提议，请参考文档中的[示例](https://xuri.me/excelize/zh-hans/stream.html#NewStreamWriter)，通过指定 `Cell` 数据类型中的 `StyleID` 字段来为每个单元格设置格式。

**Comment by xuri** [comment]
Thanks for your issue. Please reference the [example](https://xuri.me/excelize/en/stream.html#NewStreamWriter) in documentation, you can set each cell's style by specify `StyleID` field in `Cell` data type.

谢谢你的提议，请参考文档中的[示例](https://xuri.me/excelize/zh-hans/stream.html#NewStreamWriter)，通过指定 `Cell` 数据类型中的 `StyleID` 字段来为每个单元格设置格式。
