### ISSUE TITLE
delete sheet order

### ISSUE THREAD

**Issue by imbaMF** [xuri/excelize-doc#7]
hello! very big thx u for ur beaut..! stuff! 
the proble is in delete sheet, it was taken my 5 hours understand what is wrong...
when im do this
```
eo.File = excelize.NewFile()
eo.File.NewSheet(sheet)
eo.File.DeleteSheet("Sheet1")
```
the sheet1 is deleteting and new shit is creating.... but if do
```
eo.File = excelize.NewFile()
eo.File.DeleteSheet("Sheet1")
eo.File.NewSheet(sheet)
```
the sheet1 is not deleting and when i open it i have 2 sheets "sheet1" and mySheet

**Comment by xuri** [comment]
Hi @imbaMF, as the docs of the [`DeleteSheet`](https://xuri.me/excelize/en/workbook.html#DeleteSheet) noticed, it will be invalid when only one worksheet is left. If you needn't the default worksheet named `Sheet1`, you can rename it by `SetSheetName` before coming up with operations. Also, reference 360EntSecGroup-Skylar/excelize#775 and 360EntSecGroup-Skylar/excelize#780
